name: Hourly HOEP Update

on:
  schedule:
    - cron: "55 * * * *"   # Run at the 55th minute of every hour (UTC → matches EST/EDT minute 55)
  workflow_dispatch: {}     # Allow manual run from GitHub Actions tab

jobs:
  run-hourly:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed to push updated CSVs

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Optional: set API keys from GitHub Secrets if needed
      # - name: Set environment variables
      #   run: echo "MY_API_KEY=${{ secrets.MY_API_KEY }}" >> $GITHUB_ENV

      - name: Run live prediction script
        run: python live_prediction.py

      - name: Commit and push updated CSVs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/*.csv
          git commit -m "Hourly update: $(date -u +"%Y-%m-%d %H:%M:%SZ")" || echo "No changes to commit"
          git push
